# Dataset configurations
train_dataset_size: 1000
val_dataset_size: 200
img_size: 224
batch_size: 32

# Model configurations
model_type: 'resnet18'
num_classes: 2
pretrained: true

# Quantization configurations
quantization_backend: 'qnnpack'
static_quantization_calibration_batches: 10
qat_num_epochs: 1
qat_learning_rate: 0.0001

# Benchmark configurations
benchmark_num_runs: 100

# Paths
quantized_model_path: 'quantized_model.pt'

# Logging
log_file: 'quantization.log'
log_rotation: '500 MB'